### ISSUE TITLE
So i ran this code forwardly from source library

### ISSUE THREAD

**Issue by armbull** [KoushikNavuluri/Claude-API#11]
So i ran this code forwardly from source library
```import requests
import json
import os
import uuid
cookie = 'sessionKey=sk-XXX; intercom-device-id-lupk8zyo=XXX; intercom-session-lupk8zyo=XXX; __cf_bm=XXX'
def get_organization_id():
    url = "https://claude.ai/api/organizations"
    headers = {
        'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
        'Accept-Language': 'en-US,en;q=0.5',
        'Referer': 'https://claude.ai/chats',
        'Content-Type': 'application/json',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin',
        'Connection': 'keep-alive',
        'Cookie': f'{cookie}'
    }

    response = requests.request("GET", url, headers=headers)
    print(response)
    print(response.text)
    res = json.loads(response.text)
    uuid = res[0]['uuid']

    return uuid

if __name__ == "__main__":
    get_organization_id()
```
   
And got error below
```
<Response [403]>
{"error": {"type": "permission_error", "message": "We are unable to serve your request"}}
Traceback (most recent call last):
  File "XXXpath/txt.py", line 31, in <module>
    get_organization_id()
  File "XXXpath/txt.py", line 26, in get_organization_id
    uuid = res[0]['uuid']
KeyError: 0
```

Seems Error is 403
```
{"error": {"type": "permission_error", "message": "We are unable to serve your request"}}
```

My IP (VPN) is US, i have an access from browser to claude,
Also I've tried to change userAgent (I am from macos), there is no result.

_Originally posted by @armbull in https://github.com/KoushikNavuluri/Claude-API/issues/10#issuecomment-1647766855_

After upgrade to latest version, it also doesn't work. It shows same error

**Comment by KoushikNavuluri** [comment]
Hey, @armbull It will not be working via vpn  , in such case try to use proxies.
