### ISSUE TITLE
Error: json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)

### ISSUE THREAD

**Issue by user-AC** [KoushikNavuluri/Claude-API#60]
Thanks for the Great Work!

I'm having trouble running
> python ./usecases/console_chat.py 

The error is
```
Traceback (most recent call last):
  File "console_chat.py", line 33, in <module>
    main()
  File "console_chat.py", line 13, in main
    claude = Client(cookie)
  File "/home/paul/anaconda3/envs/TA/lib/python3.8/site-packages/claude_api.py", line 13, in __init__
    self.organization_id = self.get_organization_id()
  File "/home/paul/anaconda3/envs/TA/lib/python3.8/site-packages/claude_api.py", line 32, in get_organization_id
    res = json.loads(response.text)
  File "/home/paul/anaconda3/envs/TA/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/paul/anaconda3/envs/TA/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/paul/anaconda3/envs/TA/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)
```

**I read all issues and readme.md carefully,** but still can't find a solution.

I noticed that there are a few oddities when getting cookies:
* First, I can't find the exact same response as your readme.me in the Network Tab, such as 'File: organizations, Type: html'. My My screenshot is as follows (and I click the 1st row to copy the cookies):
<img width="1285" alt="截屏2023-08-20 23 11 10" src="https://github.com/KoushikNavuluri/Claude-API/assets/117973717/188c6ff8-dbfa-4994-8849-ac447f2fd1c4">

* Second, my cookies contains 5 values, they are:
```
cf_clearance=***; 
sessionKey=sk-ant-sid01-****; 
intercom-sessionupk8zyo=RE***; 
intercom-device-id-lupk8zyo=***;
 __cf_bm=****=
```
The number of values is different from that in your readme.md (i.e., 4).

I also attach the console_chat.py for reference here:
```
import os
from claude_api import Client

def get_cookie():
    # cookie = os.environ.get('cookie')
    cookie = 'cf_clearance=***; sessionKey=sk-ant-sid01-****; intercom-sessionupk8zyo=RE***; intercom-device-id-lupk8zyo=***;
__cf_bm=****='
    if not cookie:
        raise ValueError("Please set the 'cookie' environment variable.")
    return cookie

def main():
    cookie = get_cookie()
    claude = Client(cookie)
    conversation_id = None

    print("Welcome to Claude AI Chat!")

    while True:
        user_input = input("You: ")

        if user_input.lower() == 'exit':
            print("Thank you!")
            break

        if not conversation_id:
            conversation = claude.create_new_chat()
            conversation_id = conversation['uuid']

        response = claude.send_message(user_input, conversation_id)
        print("Chatbot:", response)

if __name__ == "__main__":
    main()

```
Looking forward to your reply！

**Comment by KoushikNavuluri** [comment]
It seems to be problem with cookie.. placement, Please the whole cookie ,check for docs or readme file... .you can Also check in storage tab for required cookies.
