### ISSUE TITLE
CApath: none

### ISSUE THREAD

**Issue by baidusima** [KoushikNavuluri/Claude-API#65]
[REV]处理消息时出现错误，请联系管理员
Traceback (most recent call last):
  File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\curl_cffi\requests\session.py", line 436, in request
    c.perform()
  File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\curl_cffi\curl.py", line 191, in perform
    self._check_error(ret, action="perform")
  File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\curl_cffi\curl.py", line 84, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\curl_cffi\cacert.pem CApath: none'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\main.py", line 136, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 149, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 62, in __init__
    self.__rev_interface_impl__,_,_ = __rev_interface_impl_class__.create_instance()
  File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\impls\claude.py", line 36, in create_instance
    return ClaudeImpl(cookies), True, cookies_list
  File "C:\Users\31447\Desktop\新建文件夹 (2)\QChatGPT\.\plugins\revLibs\pkg\process\impls\claude.py", line 39, in __init__
    self.chatbot = Client(cookies)
  File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\claude_api.py", line 13, in __init__
    self.organization_id = self.get_organization_id()
  File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\claude_api.py", line 31, in get_organization_id
    response = requests.get(url, headers=headers,impersonate="chrome110")
  File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\curl_cffi\requests\__init__.py", line 46, in request
    return s.request(
  File "C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\curl_cffi\requests\session.py", line 438, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\31447\Desktop\新建文件夹 (2)\python\lib\site-packages\curl_cffi\cacert.pem CApath: none'

**Comment by st1vms** [comment]
Hello, I recently improved the existing solutions, by fixing header consistency, adding auto session gathering using Firefox login and selenium, and auto user agent retrieval along with timezone.

My unofficial version of the API does currently work like a charm, it supports chat creation/deletion/retrieval and messages with attachments (with all the supported file types). It also let you handle a MessageRateLimit exception that provides you with the amount of seconds to sleep before next rateReset. 

Come have a try! Leave a :star: if you can : )

https://github.com/st1vms/unofficial-claude2-api

**Comment by KoushikNavuluri** [comment]
Hey, @baidusima it seems like you may be using VPN .Try using proxies instead.
